import {cleanup,fireEvent,render,screen,waitFor} from '@testing-library/react';
import {afterEach,beforeEach,describe,it,expect,vi} from 'vitest';
import WorkoutTracker from './WorkoutTracker';
import {createSession,type Session} from '@/lib/tracking/model';
import {draftKey,writeDraft} from '@/lib/tracking/store';
const mocks=vi.hoisted(()=>({load:vi.fn(),save:vi.fn()}));
vi.mock('@/integrations/supabase/client',()=>({supabase:{from:()=>({select:()=>({order:async()=>({data:[],error:null})})})}}));
vi.mock('@/lib/tracking/store',async(importOriginal)=>{const actual=await importOriginal<typeof import('@/lib/tracking/store')>();return {...actual,loadSessions:mocks.load,saveSession:mocks.save,trackingDb:{from:()=>({select:()=>({eq:()=>({order:async()=>({data:[],error:null})})})})}};});
const plan={day:'Lunes',type:'gimnasio' as const,exercises:[{exercise_id:'press',name:'Press',series:12,reps:8,weight:'40',rest:'60'}]};
beforeEach(()=>{localStorage.clear();vi.clearAllMocks();mocks.load.mockResolvedValue([]);mocks.save.mockImplementation(async(p)=>({...p.session,revision:p.session.revision+1}));});afterEach(cleanup);
describe('durable sessions',()=>{
 it('recovers 10/12 from local storage after reload and finalizes partial once',async()=>{const session=createSession('user',plan);session.payload.exercises[0].sets.forEach((s,i)=>{s.done=i<10;s.actual={...s.target};});writeDraft({session,mutation:crypto.randomUUID(),reason:''});const first=render(<WorkoutTracker userId="user" dayPlans={[plan]}/>);await screen.findByRole('button',{name:/Finalizar sesión · 10/});first.unmount();render(<WorkoutTracker userId="user" dayPlans={[]}/>);const finish=await screen.findByRole('button',{name:/Finalizar sesión · 10/});await waitFor(()=>expect(finish).not.toBeDisabled());fireEvent.click(finish);await screen.findByText(/Sesión realizada. 83/);expect(mocks.save).toHaveBeenCalledTimes(1);expect(mocks.save.mock.calls[0][0].session.id).toBe(session.id);expect(localStorage.getItem(draftKey('user'))).toBeNull();});
 it('does not restore another user draft',async()=>{writeDraft({session:createSession('other',plan),mutation:crypto.randomUUID(),reason:''});render(<WorkoutTracker userId="user" dayPlans={[plan]}/>);await screen.findByRole('button',{name:'Empezar entrenamiento'});expect(screen.queryByRole('button',{name:/Finalizar sesión/})).toBeNull();});
 it('replays identical mutation after an uncertain save without duplicating session',async()=>{const session=createSession('user',plan);session.payload.exercises[0].sets[0].done=true;session.payload.exercises[0].sets[0].actual={...session.payload.exercises[0].sets[0].target};const mutation=crypto.randomUUID();writeDraft({session,mutation,reason:''});mocks.save.mockRejectedValueOnce(new Error('offline'));render(<WorkoutTracker userId="user" dayPlans={[plan]}/>);await screen.findByRole('button',{name:/Guardar ahora/});await screen.findByRole('button',{name:'Reintentar'});fireEvent.click(screen.getByRole('button',{name:'Reintentar'}));await screen.findByText('Guardado en tu cuenta');expect(mocks.save.mock.calls[0][0].mutation).toBe(mutation);expect(mocks.save.mock.calls[1][0].mutation).toBe(mutation);});
});
