// AUTO-GENERATED by @lovable.dev/mcp-js — do not edit. Regenerated by the Vite plugin.
// To take ownership, delete this banner line; the plugin then leaves the file alone.
// supabase function: mcp
// Bundled from src/lib/mcp/index.ts by @lovable.dev/mcp-js.
// src/lib/mcp/index.ts
import { auth, defineMcp } from "npm:@lovable.dev/mcp-js@0.20.0";

// src/lib/mcp/tools/get-profile.ts
import { createClient } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_profile_default = defineTool({
  name: "get_profile",
  title: "Obtener perfil del usuario",
  description: "Devuelve el perfil del usuario autenticado en Autopilot (nombre, objetivo, datos b\xE1sicos).",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = createClient(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("profiles").select("*").eq("id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { profile: data }
    };
  }
});

// src/lib/mcp/tools/get-training-plan.ts
import { createClient as createClient2 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool2 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_training_plan_default = defineTool2({
  name: "get_training_plan",
  title: "Obtener plan de entrenamiento",
  description: "Devuelve el plan de entrenamiento actual del usuario autenticado en Autopilot.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = createClient2(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("training_plan").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { training_plan: data }
    };
  }
});

// src/lib/mcp/tools/get-nutrition-plan.ts
import { createClient as createClient3 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool3 } from "npm:@lovable.dev/mcp-js@0.20.0";
var get_nutrition_plan_default = defineTool3({
  name: "get_nutrition_plan",
  title: "Obtener plan de nutrici\xF3n",
  description: "Devuelve el plan de nutrici\xF3n actual (macros y comidas) del usuario autenticado en Autopilot.",
  inputSchema: {},
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async (_input, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const sb = createClient3(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("nutrition_plan").select("*").eq("user_id", ctx.getUserId()).maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data) }],
      structuredContent: { nutrition_plan: data }
    };
  }
});

// src/lib/mcp/tools/list-weight-logs.ts
import { createClient as createClient4 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool4 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z } from "npm:zod@^4.4.3";
var list_weight_logs_default = defineTool4({
  name: "list_weight_logs",
  title: "Listar registros de peso",
  description: "Devuelve los \xFAltimos registros de peso corporal del usuario autenticado, m\xE1s recientes primero.",
  inputSchema: {
    limit: z.number().int().describe("N\xFAmero m\xE1ximo de registros a devolver (1-100).").optional()
  },
  annotations: { readOnlyHint: true, idempotentHint: true, openWorldHint: false },
  handler: async ({ limit }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    const n = Math.min(Math.max(Number(limit ?? 30), 1), 100);
    const sb = createClient4(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("weight_logs").select("*").eq("user_id", ctx.getUserId()).order("created_at", { ascending: false }).limit(n);
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: JSON.stringify(data ?? []) }],
      structuredContent: { weight_logs: data ?? [] }
    };
  }
});

// src/lib/mcp/tools/log-weight.ts
import { createClient as createClient5 } from "npm:@supabase/supabase-js@^2.98.0";
import { defineTool as defineTool5 } from "npm:@lovable.dev/mcp-js@0.20.0";
import { z as z2 } from "npm:zod@^4.4.3";
var log_weight_default = defineTool5({
  name: "log_weight",
  title: "Registrar peso",
  description: "Guarda un nuevo registro de peso corporal (en kilogramos) para el usuario autenticado.",
  inputSchema: {
    weight_kg: z2.number().describe("Peso corporal en kilogramos (por ejemplo 78.5)."),
    note: z2.string().describe("Nota opcional sobre el registro.").optional()
  },
  annotations: { readOnlyHint: false, destructiveHint: false, idempotentHint: false, openWorldHint: false },
  handler: async ({ weight_kg, note }, ctx) => {
    if (!ctx.isAuthenticated()) {
      return { content: [{ type: "text", text: "No autenticado" }], isError: true };
    }
    if (!Number.isFinite(weight_kg) || weight_kg <= 20 || weight_kg > 400) {
      return { content: [{ type: "text", text: "Peso fuera de rango (20-400 kg)" }], isError: true };
    }
    const sb = createClient5(process.env.SUPABASE_URL, process.env.SUPABASE_PUBLISHABLE_KEY, {
      global: { headers: { Authorization: `Bearer ${ctx.getToken()}` } },
      auth: { persistSession: false, autoRefreshToken: false }
    });
    const { data, error } = await sb.from("weight_logs").insert({ user_id: ctx.getUserId(), weight_kg, note: note ?? null }).select().maybeSingle();
    if (error) return { content: [{ type: "text", text: error.message }], isError: true };
    return {
      content: [{ type: "text", text: `Peso registrado: ${weight_kg} kg` }],
      structuredContent: { weight_log: data }
    };
  }
});

// src/lib/mcp/index.ts
var projectRef = "enebrcdrdnfkyduzyrzm";
var mcp_default = defineMcp({
  name: "autopilot-mcp",
  title: "Autopilot",
  version: "0.1.0",
  instructions: "Herramientas de Autopilot para asistentes conectados por MCP. Permiten leer el perfil, el plan de entrenamiento y de nutrici\xF3n del usuario autenticado, listar registros de peso y a\xF1adir un nuevo registro de peso. Todas las llamadas se ejecutan como el usuario que ha autorizado el cliente (Supabase RLS).",
  auth: auth.oauth.issuer({
    issuer: `https://${projectRef}.supabase.co/auth/v1`,
    acceptedAudiences: "authenticated"
  }),
  tools: [get_profile_default, get_training_plan_default, get_nutrition_plan_default, list_weight_logs_default, log_weight_default]
});

// lovable-mcp-supabase-entry.ts
import { createSupabaseHandler } from "npm:@lovable.dev/mcp-js@0.20.0/stacks/supabase";
Deno.serve(createSupabaseHandler(mcp_default, { functionName: "mcp" }));
